name: "@web3actions/ethtx"
description: A GitHub Action to send Ethereum transactions.
branding:
  icon: trending-up
  color: purple
inputs:
  rpc-node:
    description: An ethereum RPC node. Alternatively you can set a network name and an infura key.
    required: false
  network:
    description: An ethereum network name (e.g. kovan, mainnet or polygon-mumbai).
    required: false
  infura-key:
    description: An infura key.
    required: false
  wallet-key:
    desciption: The key for the account that sends the transaction.
    required: false
    default: null
  to:
    description: The receiving address. If provided a GitHub username or username and repo instead, the action will try to fetch the address from that repo's config.
    required: false
    default: null
  message:
    description: Addtional data for transactions to external addresses.
    required: false
    default: null
  contract:
    description: The address of the contract you want to call.
    required: false
    default: null
  function:
    description: The function name, input and return types (e.g. myFunc(uint256,address) returns(bool)) in case of contract interaction.
    required: false
    default: null
  inputs:
    description: The JSON encoded function input values in case of contract interaction.
    required: false
    default: null
  gas-limit:
    description: The maximum gas to spend on a transaction.
    required: false
    default: null
  signer:
    description: A repository with a signer workflow.
    required: false
    default: null
  github-token:
    description: A token to make API calls. Only required when using a signer.
    required: false
    default: null
  contract-address:
    description: represents the pairs address see -> https://docs.chain.link/docs/ethereum-addresses/
    required: true
    default: null
  contract-decimals:
    description: represents the pairs decimal requirements for mathing see -> https://docs.chain.link/docs/ethereum-addresses/
    required: true
    default: null
  labels:
    description: the labels provided on a particular pull request comma delimited
    required: true
    default: null
outputs:
  result:
    description: The JSON encoded transaction object or return value.
runs:
  using: node12
  main: dist/index.js
