name: transaction
description: A GitHub Action to send Ethereum transactions.
inputs:
  rpc-node:
    description: An ethereum RPC node.
    required: true
  wallet-key:
    desciption: The key for the account that sends the transaction.
    required: false
    default: null
  to:
    description: The receiving address. If provided a GitHub username or username and repo instead, the action will try to fetch the address from that repo's config.
    required: false
    default: null
  value:
    description: The value transferred for the transaction (in ether).
    required: false
    default: null
  message:
    description: Addtional data for transactions to external addresses.
    required: false
    default: null
  contract:
    description: The address of the contract you want to call.
    required: false
    default: null
  function:
    description: The function name, input and return types (e.g. myFunc(uint256,address) returns(bool)) in case of contract interaction.
    required: false
    default: null
  inputs:
    description: The JSON encoded function input values in case of contract interaction.
    required: false
    default: null
  gas-limit:
    description: The maximum gas to spend on a transaction.
    required: false
    default: null
outputs:
  result:
    description: The JSON encoded transaction object or return value.
runs:
  using: node12
  main: dist/index.js
